### ISSUE TITLE
PrivacyAgent.add_conversation() rejects model/provider kwargs → assistant turns 500 (regression from #1906)

### ISSUE THREAD

**Issue by UncleSaurus** [KestrelSovereignAI/kestrel-sovereign#1920]
## Summary
On current `main` (`dcd885b0`, from #1906 "Voice/model truth — slice A"), persisting an assistant turn through the privacy wrapper raises:

```
TypeError: PrivacyAgent.add_conversation() got an unexpected keyword argument 'model'
```

This happens on essentially every assistant turn once a model/provider identity is resolved (i.e. after the first turn), so the chat-turn persistence path 500s.

## Root cause
#1906 added `model`/`provider` columns and threaded them through the **storage** layer:
- `kestrel_sovereign/storage/async_storage.py:223-224` — `add_conversation(..., model=None, provider=None)`
- `kestrel_sovereign/storage/privacy_wrapper.py:363-364` — same

…and updated the callers to forward them as `**kwargs`:
- [`kestrel_sovereign/kestrel_agent.py:2638-2648`](kestrel_sovereign/kestrel_agent.py#L2638-L2648) — builds `kwargs["model"]/["provider"]` then `self.privacy_agent.add_conversation("assistant", content, **kwargs)`
- [`kestrel_sovereign/agent/streaming.py:1599-1612`](kestrel_sovereign/agent/streaming.py#L1599-L1612) — same pattern

But the **agent-level** wrapper `PrivacyAgent.add_conversation` was NOT updated and still has the old signature:
- [`kestrel_sovereign/features/privacy/feature.py:236-238`](kestrel_sovereign/features/privacy/feature.py#L236-L238)
  ```python
  async def add_conversation(self, role, content, metadata=None,
                             session_id=None, rendered_content=None):
  ```
So when `kwargs` contains `model`/`provider`, the `**kwargs` spread hits this wrapper and raises `TypeError`.

## Repro
Boot a fresh single-agent host and take 2+ chat turns (the second resolves a model identity → passes `model=` → 500). Surfaced while booting a throwaway host for the #1825 QR e2e work.

## Fix
Add `model: Optional[str] = None` and `provider: Optional[str] = None` to `PrivacyAgent.add_conversation` and forward them to the underlying storage `add_conversation` call (the storage/privacy_wrapper layer already accepts them). Consider a contract test that asserts `PrivacyAgent.add_conversation`'s signature stays a superset of the storage `add_conversation` signature so this class of drift is caught.

## Notes
- Found incidental to #1825 / #1918 (QR-in-chat) — unrelated to that change.
- Severity: blocks normal chat-turn persistence on current `main`; should be verified against deployed agents (their running build may predate #1906).

**Comment by UncleSaurus** [comment]
Live forensic confirmation (post-`kestrel update`, 2026-06-28).

The new `assistant_turn_persist_failed` read path (#969 item 2 / #2006) lets us see this regression's real-world footprint directly in the agents' `a2a_observability`:

- **Emma: 3 failures**, all `TypeError: PrivacyAgent.add_conversation() got an unexpected keyword argument 'model'`, session 1288 — at 2026-06-23T19:21Z, 2026-06-24T16:03Z, 2026-06-24T16:04Z. Those three assistant turns failed to persist (the exact symptom).
- **Meridian / Claw / Nellie: 0.**
- This fix (#1921) merged **2026-06-24T16:14Z — ~10 min after Emma's last failure**.
- **0 occurrences on any agent since the merge.** Current live code accepts `model`/`provider`.

Resolution verified on live data; nothing further needed.
